### ISSUE TITLE
Unable to play songs when set to multiple tracks 1.10.2

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Vazkii/Ambience#30]
[18:30:08] [Ambience Player Thread/INFO] [STDERR]: [vazkii.ambience.SongLoader:getStream:104]: java.io.FileNotFoundException: D:\Video-Games-Collection\Minecraft\Launcher\Multi Minecraft\instances\MC-1.10.2-Project-Rachel-v00001\minecraft\ambience_music\music\TitleScreen1,TitleScreen2.mp3 (The system cannot find the file specified)
[18:30:08] [Ambience Player Thread/INFO] [STDERR]: [vazkii.ambience.SongLoader:getStream:104]: 	at java.io.FileInputStream.open0(Native Method)
[18:30:08] [Ambience Player Thread/INFO] [STDERR]: [vazkii.ambience.SongLoader:getStream:104]: 	at java.io.FileInputStream.open(Unknown Source)
[18:30:08] [Ambience Player Thread/INFO] [STDERR]: [vazkii.ambience.SongLoader:getStream:104]: 	at java.io.FileInputStream.<init>(Unknown Source)
[18:30:08] [Ambience Player Thread/INFO] [STDERR]: [vazkii.ambience.SongLoader:getStream:104]: 	at vazkii.ambience.SongLoader.getStream(SongLoader.java:101)
[18:30:08] [Ambience Player Thread/INFO] [STDERR]: [vazkii.ambience.SongLoader:getStream:104]: 	at vazkii.ambience.PlayerThread.run(PlayerThread.java:52)
[18:30:08] [Ambience Player Thread/ERROR] [FML]: File D:\Video-Games-Collection\Minecraft\Launcher\Multi Minecraft\instances\MC-1.10.2-Project-Rachel-v00001\minecraft\ambience_music\music\TitleScreen1,TitleScreen2.mp3 not found. Fix your Ambience config!

https://www.dropbox.com/s/trktk6zqvxa16p0/ambience_music.zip?dl=1 

There is nothing wrong with config or files. :/

**Comment by P3rf3ctXZer0** [comment]
Okay update time! @Vazkii if you find this it seems to work fine with biomes but causes aforementioned issues with events. I have yet to test primary and secondary tags.

**Comment by P3rf3ctXZer0** [comment]
Doesn't work as intended.
